In [10]:
import pandas as pd

from IPython.display import display

import plotly.express as px

Here we get the first few rows of our data, aswell as the total number of inversion periods. We see that an inversion is a uncommon event.

In [11]:
df = pd.read_csv("D:/Users/nickt/ECO482/Research Project Files/Cleaning/FRED_MD_Cleaned.csv")

df_1 = pd.read_csv("D:/Users/nickt/ECO482/Research Project Files/Cleaning/FRED_MD_Cleaned_NonTransformed.csv")

display(df.head())

df['Inversion'].value_counts()

,sasdate,RPI,W875RX1,DPCERA3M086SBEA,CMRMTSPLx,RETAILx,INDPRO,IPFPNSS,IPFINAL,IPCONGD,...,CES2000000008,CES3000000008,UMCSENTx,DTCOLNVHFNM,DTCTHFNM,INVEST,VIXCLSx,Slope,Inversion,Target_6M
0,1963-03-01,0.004511,0.004468,0.005060,-0.008901,0.007959,0.006133,0.000000,0.001013,0.004051,...,0.003361,-0.000019,-2.233333,0.003433,0.001596,0.000909,12.3661,1.04,0,0.0
1,1963-04-01,0.002740,0.002827,0.003623,0.021836,0.004324,0.009131,0.011152,0.005051,0.004038,...,-0.020316,-0.004320,-2.233333,0.011471,0.008035,0.003208,11.6621,1.07,0,0.0
2,1963-05-01,0.004270,0.004225,0.000621,0.006193,-0.006345,0.012051,0.004021,0.000000,0.002010,...,0.023746,0.004301,-2.233333,0.001426,0.000979,-0.000537,12.2422,1.00,0,0.0
3,1963-06-01,0.004702,0.005151,0.009609,-0.012681,0.007423,0.002990,0.002006,0.004026,0.006014,...,-0.003453,-0.000018,1.566667,0.001852,0.003576,0.003330,12.0403,1.00,0,0.0
4,1963-07-01,0.000563,0.000594,0.005132,0.027610,0.011540,-0.003988,0.000000,0.000000,-0.003002,...,-0.003384,-0.000018,1.566667,-0.003053,-0.002098,0.001603,14.2966,0.84,0,0.0

Inversion
0    642
1     93
Name: count, dtype: int64

Below we plot the Slope variable, to see the yield curve inversions over time. All points below the black line are times when the yield curve was inverted.

In [12]:
plt = px.line(df, x="sasdate", y="Slope", title="Slope of the Yield Curve Over Time")

plt.add_hline(y=0)

plt.show()

We can display some summary statistics of our cleaned data (Pre Transformation). Keep in mind, these are the transformed values of our data.

In [13]:
cols = ['GS10', 'TB3MS', 'Slope', 'UNRATE', 'S&P 500']

summary_stats = df_1[cols].agg(['mean', 'std', 'min', 'max']).transpose()

summary_stats.columns = ['Mean', 'Std Dev', 'Min', 'Max']

print("="*50)
print("DATASET SUMMARY STATISTICS")
print("="*50)
print(summary_stats.round(2))

print(len(df_1.columns))

display(df_1[cols].corr())

==================================================
DATASET SUMMARY STATISTICS
==================================================
            Mean  Std Dev    Min      Max
GS10        5.88     2.97   0.62    15.32
TB3MS       4.46     3.19   0.01    16.30
Slope       1.42     1.28  -2.65     4.42
UNRATE      5.88     1.73   3.40    14.80
S&P 500  1021.02  1232.60  65.06  6010.91
126

             GS10     TB3MS     Slope    UNRATE   S&P 500
GS10     1.000000  0.916557  0.033921  0.291344 -0.606031
TB3MS    0.916557  1.000000 -0.368584  0.046540 -0.477517
Slope    0.033921 -0.368584  1.000000  0.560930 -0.215354
UNRATE   0.291344  0.046540  0.560930  1.000000 -0.292570
S&P 500 -0.606031 -0.477517 -0.215354 -0.292570  1.000000